# Generated by Django 6.0 on 2026-03-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='native_language',
            field=models.CharField(choices=[('no', 'Norwegian'), ('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('uk', 'Ukrainian'), ('ar', 'Arabic'), ('tr', 'Turkish'), ('fa', 'Persian (Farsi)'), ('ru', 'Russian'), ('ps', 'Pashto'), ('prs', 'Dari'), ('ur', 'Urdu'), ('ku', 'Kurdish (Kurmanji)'), ('ckb', 'Kurdish (Sorani)'), ('bn', 'Bengali'), ('zh-Hans', 'Chinese Simplified'), ('vi', 'Vietnamese'), ('th', 'Thai'), ('so', 'Somali'), ('ti', 'Tigrinya'), ('am', 'Amharic'), ('om', 'Oromo'), ('sw', 'Swahili'), ('pl', 'Polish'), ('sr-Latn', 'Serbian (Latin)'), ('bs', 'Bosnian'), ('hr', 'Croatian'), ('sq', 'Albanian')], default='en', max_length=25, verbose_name='Native Language'),
        ),
    ]
