# Generated by Django 6.0 on 2026-01-31 15:49

import apps.chat.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DangerKeyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='Det farlige ordet (norsk)')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EpidemicAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symptom_category', models.CharField(max_length=100, verbose_name='Possible type of epidemic')),
                ('case_count', models.IntegerField(verbose_name='Number of cases detected')),
                ('time_window_hours', models.IntegerField(default=1, verbose_name='Within (hours)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='Reviewed/Processed')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ImageAnalysisCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('cached_image', models.ImageField(blank=True, null=True, upload_to='cache_snapshots/%Y/', verbose_name='Snapshot')),
                ('analysis_result', apps.chat.models.EncryptedTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('priority', models.IntegerField(choices=[(1, 'Nurse (Normal)'), (2, 'Doctor (Urgent)')], default=1, verbose_name='Priority Level')),
                ('nurse', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_sessions', to=settings.AUTH_USER_MODEL)),
                ('refugee', models.ForeignKey(limit_choices_to={'role': 'REFUGEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_original', apps.chat.models.EncryptedTextField(blank=True, null=True, verbose_name='Original Text')),
                ('language_code', models.CharField(blank=True, max_length=10)),
                ('text_translated', apps.chat.models.EncryptedTextField(blank=True, null=True, verbose_name='Translated Text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/%Y/%m/', verbose_name='Medical Image')),
                ('ai_analysis', apps.chat.models.EncryptedTextField(blank=True, null=True, verbose_name='AI Medical Analysis')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Urgent / Doctor')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('source_language', models.CharField(max_length=10)),
                ('target_language', models.CharField(max_length=10)),
                ('source_text', apps.chat.models.EncryptedTextField()),
                ('translated_text', apps.chat.models.EncryptedTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('source_hash', 'source_language', 'target_language')},
            },
        ),
    ]
