# Generated by Django 6.0 on 2026-02-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_cannedresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cannedresponse',
            name='title',
        ),
    ]
